include: package:lints/recommended.yaml

# https://dart-lang.github.io/linter/lints/
analyzer:
  exclude:
    - example/**
    - build/**
  errors:
    unused_import: warning
    unused_local_variable: warning
    public_member_api_docs: warning

linter:
  rules:
    hash_and_equals: false
    public_member_api_docs: true
    # - package_api_docs