name: git_hooks
description: Prevents bad commit or push (git hooks, pre-commit/precommit, pre-push/prepush, post-merge/postmerge and all that stuff...).
version: 0.0.4
homepage: https://github.com/xuzhongpeng/git_hooks
author: xuzhongpeng <xuzhongpeng@foxmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: ^1.6.0
  yaml: ^2.1.0

executables:
  git_hooks:
