name: git_hooks
description: Prevents bad commit or push (git hooks, pre-commit/precommit, pre-push/prepush, post-merge/postmerge and all that stuff...).
version: 0.0.1
homepage: https://www.example.com
author: xuzhongpeng <1452754335@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0

executables:
  git_hooks:
